# Generated by Django 5.2.7 on 2025-10-04 13:41

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disaster_type', models.CharField(choices=[('flood', 'Flood'), ('fire', 'Fire'), ('accident', 'Accident'), ('collapse', 'Building Collapse')], help_text='Type of disaster incident', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the incident')),
                ('latitude', models.FloatField(help_text='Latitude coordinate of the incident location')),
                ('longitude', models.FloatField(help_text='Longitude coordinate of the incident location')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('investigating', 'Under Investigation')], default='active', help_text='Current status of the incident', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Optional image of the incident', null=True, upload_to='disaster_images/')),
                ('reporter_id', models.CharField(blank=True, help_text='Optional identifier for the reporter', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the report was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the report was last updated')),
            ],
            options={
                'verbose_name': 'Disaster Report',
                'verbose_name_plural': 'Disaster Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['disaster_type'], name='reports_dis_disaste_9f9a9e_idx'), models.Index(fields=['status'], name='reports_dis_status_ef4927_idx'), models.Index(fields=['created_at'], name='reports_dis_created_1ef597_idx'), models.Index(fields=['latitude', 'longitude'], name='reports_dis_latitud_9b3c9f_idx')],
            },
        ),
    ]
