# Generated by Django 3.2.25 on 2025-10-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisasterReport',
        ),
    ]
